// <auto-generated />
namespace Personal_Inventory_Management.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addrequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addrequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201712050314114_add required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
